# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd = {
    luks.devices.crypt = {
      device = "/dev/disk/by-uuid/97191312-662e-445a-a662-d7ae50a17959";
      preLVM = true;
      keyFile = "keyfile.bin";
      allowDiscards = true;
      fallbackToPassword = true;
    };
    secrets."keyfile.bin" = "/etc/secrets/initrd/keyfile.bin";
  };

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/daac1507-a57a-4ad3-be19-288fc699c46f";
      fsType = "xfs";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/D2C8-D8EE";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/f0728dbc-7558-4e36-a6c0-4dceb133c1f2"; }];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableAllFirmware = true;
}
